execute immediate $$
begin
    USE DATABASE MLG_SNOWFLAKE;
    USE SCHEMA UTILITY;
    USE ROLE SYSADMIN;

    return 'Initiated the context';
end;
$$;

-- Test CREATE_TABLE_FROM_S3_GET_FILE_HEADER_COLUMNS
CALL MLG_SNOWFLAKE.UTILITY
  .CREATE_TABLE_FROM_S3_GET_FILE_HEADER_COLUMNS('@MLG_SNOWFLAKE.PUBLIC.MLG_SNOWFLAKE_STAGE/Lead.txt');


-- Test CREATE_TABLE_FROM_S3
DROP TABLE IF EXISTS MLG_SNOWFLAKE.UTILITY.LEAD_1;
CALL MLG_SNOWFLAKE.UTILITY.CREATE_TABLE_FROM_S3('MLG_SNOWFLAKE.UTILITY.LEAD_1',
	'@MLG_SNOWFLAKE.PUBLIC.MLG_SNOWFLAKE_STAGE/Lead.txt');


-- Drop the test table
DROP TABLE IF EXISTS MLG_SNOWFLAKE.UTILITY.LEAD_1;

