-- Clean up
DROP PROCEDURE IF EXISTS CREATE_TABLE(VARCHAR, VARCHAR, VARCHAR);
DROP FILE FORMAT IF EXISTS CSV_WHOLE_LINE;
DROP STAGE IF EXISTS S3_HUGE_HEAD_LI_2022_STAGE;
DROP storage integration IF EXISTS S3_HUGE_HEAD_LI_2022;

DROP TABLE IF EXISTS AAAA;