USE DATABASE MLG_SNOWFLAKE;
USE SCHEMA UTILITY;
USE ROLE SYSADMIN;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

DROP FUNCTION IF EXISTS GET_CONFORMING_DATE(FLOAT, DATE, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT);