execute immediate $$
begin
    USE DATABASE MLG_SNOWFLAKE;
    USE SCHEMA UTILITY;
    USE ROLE SYSADMIN;

    return 'Initiated the context';
end;
$$;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

CALL MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_TABLE('MLG_SNOWFLAKE.UTILITY.LEAD', 'MLG_SNOWFLAKE.UTILITY.LEAD');
CALL MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_TABLE_DIFF_ONLY('MLG_SNOWFLAKE.UTILITY.LEAD', 'MLG_SNOWFLAKE.UTILITY.LEAD');

CALL MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_S3_FILE_HEADER('MLG_SNOWFLAKE.UTILITY.LEAD',
    '@MLG_SNOWFLAKE.PUBLIC.MLG_SNOWFLAKE_STAGE/Lead.txt');
CALL MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_S3_FILE_HEADER_DIFF_ONLY('MLG_SNOWFLAKE.UTILITY.LEAD',
    '@MLG_SNOWFLAKE.PUBLIC.MLG_SNOWFLAKE_STAGE/Lead.txt');


DROP PROCEDURE MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_TABLE(VARCHAR, VARCHAR);
DROP PROCEDURE MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_TABLE_DIFF_ONLY(VARCHAR, VARCHAR);
DROP PROCEDURE MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_S3_FILE_HEADER(VARCHAR, VARCHAR);
DROP PROCEDURE MLG_SNOWFLAKE.UTILITY.COMPARE_TABLE_TO_S3_FILE_HEADER_DIFF_ONLY(VARCHAR, VARCHAR);