SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

DROP TASK IF EXISTS TSLEEP_Task;
DROP PROCEDURE IF EXISTS TSLEEP();

DROP storage integration IF EXISTS S3_HUGE_HEAD_LI_2022;
DROP STAGE IF EXISTS S3_HUGE_HEAD_LI_2022_AAA;
DROP FILE FORMAT IF EXISTS CSV_FILE_HEADER;
DROP PROCEDURE IF EXISTS CREATE_TABLE(VARCHAR);
DROP TABLE IF EXISTS AAAA;
