USE ROLE SYSADMIN;
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();


execute immediate $$
begin
    let TABLE_NAME VARCHAR := 'MLG_SNOWFLAKE.UTILITY.BANKRUPTCY';
    let FILE_PATH VARCHAR := '@MLG_SNOWFLAKE.DATA_INTEGRATIONS.DMAP_SNOWFLAKE_STAGE/newcorelogic/bankruptcy_delta.txt';
    let KEYS VARCHAR := 'COUNTY_FIPS_CODE|BANKRUPTCY_ID';

    DROP TABLE IF EXISTS identifier(:TABLE_NAME);
    CALL MLG_SNOWFLAKE.UTILITY.CREATE_TABLE_FROM_S3(:TABLE_NAME, :FILE_PATH);
    CALL MLG_SNOWFLAKE.UTILITY.LOAD_INCREMENTAL_FROM_S3(:TABLE_NAME, :FILE_PATH, :KEYS);

    return 'Procedure called';
end;
$$;

SELECT COUNT(*) FROM MLG_SNOWFLAKE.UTILITY.BANKRUPTCY;
DROP TABLE IF EXISTS MLG_SNOWFLAKE.UTILITY.BANKRUPTCY;