USE ROLE SYSADMIN;
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();


execute immediate $$
begin
    let TABLE_NAME VARCHAR := 'MLG_SNOWFLAKE.UTILITY.ASR';
    let FILE_PATH VARCHAR := '@MLG_SNOWFLAKE.DATA_INTEGRATIONS.DMAP_SNOWFLAKE_STAGE/newcorelogic/asr_delta.txt';

    DROP TABLE IF EXISTS identifier(:TABLE_NAME);
    CALL MLG_SNOWFLAKE.UTILITY.CREATE_TABLE_FROM_S3(:TABLE_NAME, :FILE_PATH);
    CALL MLG_SNOWFLAKE.UTILITY.LOAD_FULL_REPLACE_FROM_S3(:TABLE_NAME, :FILE_PATH);

    return 'Procedure called';
end;
$$;

SELECT COUNT(*) FROM MLG_SNOWFLAKE.UTILITY.ASR;
DROP TABLE IF EXISTS MLG_SNOWFLAKE.UTILITY.ASR;