USE ROLE SYSADMIN;
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();


CALL MLG_SNOWFLAKE.UTILITY.LOAD_UTIL_LIST_FILES_FROM_S3('@MLG_SNOWFLAKE.DATA_INTEGRATIONS.DMAP_SNOWFLAKE_STAGE/newcorelogic/delta_history/divorce_delta/');