SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

USE DATABASE MLG_SNOWFLAKE;
USE SCHEMA PUBLIC;
USE ROLE SYSADMIN;

SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

USE SCHEMA UTILITY;

-- This table is expected to created in UTILITY schema
CREATE TABLE AAAA_TEST (
  C1 VARCHAR,
  C2 VARCHAR
);

DESC TABLE AAAA_TEST;

DROP TABLE IF EXISTS AAAA_TEST;
