SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

DROP storage integration IF EXISTS S3_HUGE_HEAD_LI_2022;
DROP STAGE IF EXISTS S3_HUGE_HEAD_LI_2022_AAA;
DROP TABLE IF EXISTS AAAA;
DROP pipe IF EXISTS AAAA_PIPE;